apiVersion: v2
appVersion: "1.0"
description: Helm chart for deploying Ory Keto
name: keto
version: 0.1.0

dependencies:
  - name: postgresql
    version: 8.0.0
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
