deployment:
  replicaCount: "1"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: 512Mi
xp-management-postgresql:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    size: 5Gi
