global:
  protocol: http

  mlp:
    apiPrefix: ""
    serviceName: mlp
    externalPort: "8080"
    vsPrefix: "/api"
    useServiceFqdn: true
    uiPrefix: "/"
    uiServiceName: mlp

extraLabels:
  test: 123
deployment:
  replicaCount: "1"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: 512Mi
xp-management-postgresql:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    size: 5Gi
