{{- if .Values.fluentdConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timber-fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "timber-fluentd.labels" . | nindent 4 }}
data:
  fluent.conf: |-
{{ .Values.fluentdConfig | nindent 4}}
{{- end }}