mlp:
  deployment:
    replicaCount: "1"
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: "50m"
        memory: 512Mi
merlin:
  deployment:
    replicaCount: "1"
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: "50m"
        memory: 512Mi
  swagger:
    enabled:
      false
  imageBuilder:
    clusterName: "chart-testing"
  vault:
    enabled: false
  environmentConfigs:
    - name: "chart-testing"
      is_default: true
      cluster: "chart-testing"
      region: "id"
      gcp_project: "gcp-project"
      deployment_timeout: "10m"
      namespace_timeout: "2m"
      max_cpu: "8"
      max_memory: "8Gi"
      queue_resource_percentage: "20"
      is_prediction_job_enabled: true
      is_default_prediction_job: true
      default_prediction_job_config:
        executor_replica: 3
        driver_cpu_request: "2"
        driver_memory_request: "2Gi"
        executor_cpu_request: "2"
        executor_memory_request: "2Gi"
      default_deployment_config:
        min_replica: 0
        max_replica: 1
        cpu_request: "500m"
        memory_request: "500Mi"
      default_transformer_config:
        min_replica: 0
        max_replica: 1
        cpu_request: "500m"
        memory_request: "500Mi"
  merlin-postgresql:
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: "50m"
        memory: 512Mi
    persistence:
      size: 5Gi
  mlflow:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "150m"
        memory: 512Mi
  mlflow-postgresql:
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: "50m"
        memory: 512Mi
    persistence:
      enabled: true
      size: 5Gi
  minio:
    enabled: false
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
  setupScript:
    # -- Image used to for setup scripts job
    image: bitnami/kubectl:latest
    clusterType: kind
  kserve:
    enabled: false
postgresql:
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
    limits:
      cpu: "50m"
      memory: 512Mi
  persistence:
    enabled: true
    size: 5Gi
base:
  # -- Set to false if there is an existing istio deployment
  enabled: true
  validationURL: ""
  global:
    istioNamespace: "istio-system"
istiod:
  enabled: true
  chartValues:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 250m
        memory: 512Mi
istioIngressGateway:
  global:
    enabled: false
clusterLocalGateway:
  global:
    enabled: false
cert-manager:
  fullnameOverride: cert-manager
  enabled: true
turing:
  deployment:
    replicaCount: "1"
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: "70m"
        memory: 512Mi
  environmentConfigs:
    - name: chart-testing

xp-treatment:
  deployment:
    replicaCount: "1"
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: "50m"
        memory: 512Mi

xp-management:
  deployment:
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        cpu: "50m"
        memory: 512Mi

caraml-routes:
  oathkeeper:
    enabled: true
  oathkeeperRules:
    enabled: true
