merlin:
  deployment:
    replicaCount: "1"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "500m"
        memory: 512Mi

  imageBuilder:
    clusterName: "chart-testing"

  vault:
    enabled: true
    secretName: "vault-secret"

    helmChart:
      chart: vault
      repository: https://helm.releases.hashicorp.com
      version: 0.19.0
      release: vault
      namespace: vault
      createNamespace: true
    chartValues:
      injector:
        enabled: false
      server:
        # -- This is just for quick install. For a production, NEVER EVER use the vault server in dev mode.
        dev:
          enabled: true
        dataStore:
          enabled: false
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
        affinity: null
        tolerations: null

  environmentConfigs:
    - name: "id-dev"
      is_default: true
      cluster: "chart-testing"
      region: "id"
      gcp_project: "gcp-project"
      deployment_timeout: "10m"
      namespace_timeout: "2m"
      max_cpu: "8"
      max_memory: "8Gi"
      queue_resource_percentage: "20"
      is_prediction_job_enabled: true
      is_default_prediction_job: true
      default_prediction_job_config:
        executor_replica: 3
        driver_cpu_request: "2"
        driver_memory_request: "2Gi"
        executor_cpu_request: "2"
        executor_memory_request: "2Gi"
      default_deployment_config:
        min_replica: 0
        max_replica: 1
        cpu_request: "500m"
        memory_request: "500Mi"
      default_transformer_config:
        min_replica: 0
        max_replica: 1
        cpu_request: "500m"
        memory_request: "500Mi"

  merlin-postgresql:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    persistence:
      size: 5Gi

  mlflow:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  mlflow-postgresql:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    persistence:
      enabled: true
      size: 5Gi

  minio:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi

  setupScript:
    # -- Image used to for setup scripts job
    image: bitnami/kubectl:latest
    clusterType: kind

  kserve:
    enabled: false

postgresql:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 5Gi

istiod:
  chartValues:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1024Mi

istioIngressGateway:
  chartValues:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

clusterLocalGateway:
  chartValues:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
