{{- if and .Values.fluentd.enabled .Values.fluentd.gcpServiceAccount.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-fluentd-secret
  labels:
    {{- include "observation-service.labels" . | nindent 4 }}
data:
  service-account.json: |-
{{ .Values.fluentd.gcpServiceAccount.account | indent 4 }}
{{- end }}
