apiVersion: v1
kind: Service
metadata:
  name: {{ template "observation-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    {{- include "observation-service.labels" . | nindent 4 }}
{{ if .Values.observationService.extraLabels -}}
{{ toYaml .Values.observationService.extraLabels | indent 4 -}}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.observationService.service.externalPort }}
      targetPort: {{ .Values.observationService.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
