apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: mlp.enabled
  name: mlp
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.4.14
- condition: merlin.enabled
  name: merlin
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.10.8
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.helm.sh/stable
  version: 7.0.2
- alias: caraml-authz
  condition: caraml-authz.enabled
  name: authz
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.1.7
- condition: caraml-routes.enabled
  name: caraml-routes
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.2
- name: common
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.8
- alias: base
  condition: base.enabled
  name: base
  repository: https://istio-release.storage.googleapis.com/charts
  version: 1.13.9
- alias: istiod
  condition: istiod.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.1
- alias: istioIngressGateway
  condition: istioIngressGateway.global.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.1
- alias: clusterLocalGateway
  condition: clusterLocalGateway.global.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.1
- alias: certManagerBase
  condition: certManagerBase.enabled
  name: cert-manager-base
  repository: https://caraml-dev.github.io/helm-charts
  version: 1.8.1
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.8.2
description: A Helm chart for deploying CaraML components
maintainers:
- email: caraml-dev@caraml.dev
  name: caraml-dev
name: caraml
type: application
version: 0.4.34
