merlin:

  imageBuilder:
    clusterName: "local-dev-1.22.7"
  environmentConfigs:
    - name: "local-dev-1.22.7"
      is_default: true
      cluster: "local-dev-1.22.7"
      region: "id"
      gcp_project: "gcp-project"
      deployment_timeout: "10m"
      namespace_timeout: "2m"
      max_cpu: "8"
      max_memory: "8Gi"
      queue_resource_percentage: "20"
      is_prediction_job_enabled: true
      is_default_prediction_job: true
      default_prediction_job_config:
        executor_replica: 3
        driver_cpu_request: "2"
        driver_memory_request: "2Gi"
        executor_cpu_request: "2"
        executor_memory_request: "2Gi"
      default_deployment_config:
        min_replica: 0
        max_replica: 1
        cpu_request: "500m"
        memory_request: "500Mi"
      default_transformer_config:
        min_replica: 0
        max_replica: 1
        cpu_request: "500m"
        memory_request: "500Mi"
