# Default values for caraml.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Tags can be used to enable features that are composed of multiple charts. They propagate across all dependencies, as long as the dependency has the same tag. When both conditions and tags are used, the condition will override the tag.
tags:
  # -- Set test-tag value, Value will be propogated to dependancies with that tag
  test-tag: false

# -- Values corresponding to component-a
component-a:
  # -- Make value true for enabling component-a
  enabled: false

# -- Values corresponding to component-b
component-b:
  # -- Make value true for enabling component-b
  enabled: false

postgresql:
  enabled: true
