apiVersion: v2
name: knative-serving-core
description: Installs Knative Serving core and CRDs.
type: application
version: 1.3.4
appVersion: "v1.3.2"
maintainers:
  - name: caraml-dev
    email: caraml-dev@caraml.dev
