apiVersion: v2
appVersion: 0.1.2
dependencies:
- alias: istiod
  condition: istiod.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.1.1
- alias: base
  condition: base.enabled
  name: base
  repository: https://istio-release.storage.googleapis.com/charts
  version: 1.13.4
- alias: istioIngressGateway
  condition: istioIngressGateway.global.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.1.0
- alias: certManagerBase
  condition: certManagerBase.enabled
  name: cert-manager-base
  repository: https://caraml-dev.github.io/helm-charts
  version: 1.8.1
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: 1.8.1
- condition: common.enabled
  name: common
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.4
description: A Helm chart for deploying CaraML networking resources
maintainers:
- email: caraml-dev@caraml.dev
  name: caraml-dev
name: caraml-routes
type: application
version: 0.1.5
