apiVersion: v2
appVersion: 0.0.1
dependencies:
- condition: mlp.enabled
  name: mlp
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.5.0
description: dap-secret-webhook is a Kubernetes pod mutating webhook for using CaraML
  Secrets in Flyte.
maintainers:
- email: caraml-dev@caraml.dev
  name: caraml-dev
name: dap-secret-webhook
type: application
version: 0.1.1
