# Default values for dap-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

deployment:
  replicaCount: 1

  service:
    type: ClusterIP
    port: 443

  webhook:
    # -- The endpoint of MLP API. Default will be set with to mlp local cluster
    mlpApiHost: ""
    serverCertPath: /etc/tls-certs/serverCert.pem
    serverKeyPath: /etc/tls-certs/serverKey.pem
    caCertPath: /etc/tls-certs/caCert.pem

  # -- Additional env var for webhook, see https://github.com/caraml-dev/dap-secret-webhook for full list of configurable
  extraEnvs: []
  # Example:
  # - name: DEMO_GREETING
  #   value: "Hello from the environment"

  resources:
    requests:
      cpu: 250m
      memory: 128Mi

  image:
    repository: ghcr.io/caraml-dev/dap-secret-webhook
    tag: 0.0.1
    pullPolicy: IfNotPresent

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the template
  # -- If create is false, existing service account name is required in the release namespace
  name: ""

rbac:
  # -- Specifies whether roles should be granted to
  create: true

tls:
  # -- Specifies whether a tls job that generate certs in secrets should be created
  # -- This can be set as false and the corresponding certs mounted in deployment.env
  create: true
  # -- Specifies which service account to run the tls job
  # -- If not set and create is true, a name is generated using the template
  # -- Service account is expected to be in the same namespace as the webhook and job
  serviceAccountName: ""
  # -- The name of the tls secret to use.
  # -- If not set and create is true, a name is generated using the template
  # -- If create is false, existing tls secret with corresponding env var configured for
  # -- webhook is required
  secretName: ""

mlp:
  enabled: true

