{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "treatment-svc.fullname" .}}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.ingress.class }}
    ingress.class: {{ . }}
    {{- end }}
  labels:
    {{- include "treatment-svc.labels" . | nindent 4 }}
spec:
  rules:
  - {{- with .Values.ingress.host }}
    host: {{ . }}
    {{- end }} 
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "treatment-svc.fullname" .}}
            servicePort: {{ .Values.deployment.service.externalPort }}
{{- end }}
