apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "treatment-svc.fullname" .}}-config
stringData:
  config.yaml: |
    {{- include "treatment-svc.config" . | nindent 4 -}}
