{{- if .Values.deployment.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "treatment-svc.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "treatment-svc.labels" . | nindent 4 }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
