{{- $globServiceName := include "common.get-component-value" (list .Values.global "xp-treatment" (list "serviceName")) }}
{{- if .Values.swaggerUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.set-value" (list (include "treatment-svc.fullname" .) $globServiceName) }}-swagger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "treatment-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.swaggerUi.service.type }}
  ports:
    - name: http
      port: {{ .Values.swaggerUi.service.externalPort }}
      targetPort: {{ .Values.swaggerUi.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "treatment-svc.fullname" .}}
    release: {{ .Release.Name }}
{{- end }}
