apiVersion: v1
kind: Service
metadata:
  name: {{ include "treatment-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "treatment-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deployment.service.type }}
  ports:
    - name: http
      port: {{ .Values.deployment.service.externalPort }}
      targetPort: {{ .Values.deployment.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "treatment-svc.name" .}}
    release: {{ .Release.Name }}
