global:
  # -- Extra pod labels in a map[string]string format, most likely to be used for the costing labels.
  extraPodLabels: {}

image:
  # -- Docker registry for fluentd image
  registry: ghcr.io
  # -- Docker image repository for fluentd
  repository: caraml-dev/timber/fluentd
  # -- Docker image tag for fluentd
  tag: v0.1.0
  # -- Docker image pull policy
  pullPolicy: IfNotPresent

replicaCount: 1

# -- Resources requests and limits for fluentd StatefulSet. This should be set
# according to your cluster capacity and service level objectives.
# Reference: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources: {}

# GCP configurations for flushing Observation logs to BQ
gcpServiceAccount:
  # -- Flag to toggle flushing Observation logs to BQ
  enabled: false
  # -- Base64 encoded service account json
  account: ""

# -- PVC configurations for fluentd StatefulSet storage
pvcConfig:
  name: cache-volume
  mountPath: /cache
  storage: 3Gi

# -- Kubernetes Service for fluentd StatefulSet
service:
  type: ClusterIP
  internalPort: &internalPort 9880
  externalPort: &externalPort 24224
  multiPort:
    enabled: true
  multiPorts:
    - name: tcp-input
      port: *externalPort
      targetPort: *externalPort
    - name: http-input
      port: *internalPort
      targetPort: *internalPort

# -- List of extra environment variables to add to fluentd container
extraEnvs: []

# -- List of extra labels to add to fluentd K8s resources
extraLabels: {}

# -- HPA scaling configuration for Observation Service fluentd
autoscaling:
  # -- Toggle to enable HPA scaling
  enabled: false
  # -- Minimum replicas for HPA scaling
  minReplicas: 1
  # -- Maximum replicas for HPA scaling
  maxReplicas: 2
  # -- CPU utilization percentage threshold to activate HPA scaling
  targetCPUUtilizationPercentage: 80

# -- Fluentd config to be mounted as fluentd/etc/fluent.conf
fluentdConfig: ""