apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "treatment-svc.fullname" .}}-config
stringData:
  config.yaml: |
    {{- toYaml .Values.deployment.config | nindent 4 -}}
