
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dap-secret-webhook.name" . }}-cluster-role
  labels:
    {{- include "dap-secret-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
      - mutatingwebhookconfigurations
    verbs:
      - get
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dap-secret-webhook.name" . }}-role-binding
  labels:
    {{- include "dap-secret-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dap-secret-webhook.name" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name:  {{ default (printf "%s" (include "dap-secret-webhook.name" .)) .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}