{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ default (printf "%s" (include "dap-secret-webhook.name" .)) .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
    {{- if .Values.serviceAccount.annotations }}
    annotations:
      {{- toYaml .Values.serviceAccount.annotations | nindent 6 }}
    {{ end }}
    labels:
      {{- include "dap-secret-webhook.labels" . | nindent 6 }}
{{ end }}
