{{- if .Values.tls.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "dap-secret-webhook.name" . }}-tls-sa
    namespace: {{ .Release.Namespace }}
    annotations:
      "helm.sh/hook": pre-install, pre-upgrade
      "helm.sh/hook-weight": "1"
      "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed	
{{ end }}
