apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "mlp.config-cm-name" . }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
data:
  mlp-config.yaml: |
    {{- include "mlp.config" . | nindent 4 -}}
