{{- $globOauthClientID := include "common.get-oauth-client" .Values.global }}
{{- $globApiHost := include "common.get-component-value" (list .Values.global "mlp"  (list "vsPrefix")) }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "mlp.config-cm-name" . }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
data:
  mlp-config.yaml: |
    {{- include "mlp.config" . | nindent 4 -}}
