apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlp.encryption-key-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
  annotations:
    {{- include "mlp.annotations" . | nindent 4 }}
type: Opaque
stringData:
  encryption-key: {{ .Values.encryption.key }}
