{{- if and .Values.caramlEnvironments.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlp.fullname" . }}-environments
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
type: Opaque
stringData:
  environment.yaml: |-
{{- with .Values.caramlEnvironments }}
{{- if .environmentConfigs }}
{{ toYaml .environmentConfigs | indent 4 }}
{{- end }}
  imageBuilderK8sConfig: |-
{{- if .imageBuilderConfigs }}
{{ .imageBuilderConfigs | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
