{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "mlp.fullname" .}}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
  annotations:
    {{- include "mlp.annotations" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            backend:
              serviceName: {{ template "mlp.fullname" .}}
              servicePort: {{ .Values.service.externalPort }}
{{- end }}
