{{- if and .Values.externalPostgresql.enabled .Values.externalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.password-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ template "postgres.password-secret-key" . }}: {{ .Values.externalPostgresql.password }}
{{- end -}}
