{{- if .Values.externalPostgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.password-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "mlp.name" . }}
    chart: {{ include "mlp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.externalPostgresql.password }}
{{- end -}}
