{{- if .Values.externalPostgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.password-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
  annotations:
    {{- include "mlp.annotations" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.externalPostgresql.password }}
{{- end -}}
