{{- if and .Values.externalPostgresql.enabled .Values.externalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.postgres-password-secret-name" (list .Values.postgresql .Values.externalPostgresql .Release .Chart ) | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "common.postgres-password-secret-key" (list .Values.externalPostgresql) }}: {{ .Values.externalPostgresql.password }}
{{- end -}}
