{{- if .Values.rules.enabled }}
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: {{ template "mlp.fullname" . }}-list-applications
  namespace: {{ .Release.Namespace }}
spec:
  match:
    url: <{{ .Values.rules.apiPrefixRegex }}>/applications
    methods:
      - "GET"
  authenticators:
    - handler: jwt
  authorizer:
    handler: allow
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: {{ template "mlp.fullname" . }}-get-and-create-projects
  namespace: {{ .Release.Namespace }}
spec:
  match:
    url: <{{ .Values.rules.apiPrefixRegex }}>/projects
    methods:
      - "GET"
      - "POST"
  authenticators:
    - handler: jwt
  authorizer:
    handler: allow
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: {{ template "mlp.fullname" . }}-project-sub-resources
  namespace: {{ .Release.Namespace }}
spec:
  match:
    url: <{{ .Values.rules.apiPrefixRegex }}>/projects/<[0-9]+><(/.+)?>
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
  authenticators:
    - handler: jwt
  authorizer:
    handler: remote_json
    config:
      payload: |
        {{`{"namespace": "Permission", "object": "mlp.projects.{{ printIndex .MatchContext.RegexpCaptureGroups 1 }}.{{ (print .MatchContext.Method) | lower }}", "relation": "granted", "subject_set": {"namespace": "Subject", "object": "{{ print .Extra.email }}"}}`}}
{{- end -}}
