{{- if and .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ default "mlp" .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
    annotations:
      {{- toYaml .Values.serviceAccount.annotations | nindent 6 }}
    labels:
      {{- include "mlp.labels" . | nindent 6 }}
{{ end }}
