apiVersion: v1
kind: Service
metadata:
  name: {{ template "mlp.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: http
      protocol: TCP
  selector:
    app: {{ template "mlp.name" .}}
    release: {{ .Release.Name }}
