{{ $globServiceName := include "common.get-component-value" (list .Values.global "mlp" (list "serviceName")) }}
{{- $globServicePort := include "common.get-component-value" (list .Values.global "mlp" (list "externalPort")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.set-value" (list (include "mlp.fullname" .) $globServiceName) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "common.set-value" (list .Values.service.externalPort $globServicePort)  }}
      targetPort: {{ .Values.service.internalPort }}
      name: http
      protocol: TCP
  selector:
    app: {{ template "mlp.name" .}}
    release: {{ .Release.Name }}
