deployment:
  replicaCount: "1"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: 512Mi

imageBuilder:
  clusterName: "chart-testing"

vault:
  enabled: true
  secretName: "vault-secret"

  injector:
    enabled: false
  server:
    # -- This is just for quick install. For a production, NEVER EVER use the vault server in dev mode.
    dev:
      enabled: true
    dataStore:
      enabled: false
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
    affinity: null
    tolerations: null

merlin-postgresql:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    size: 5Gi

mlflow:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

mlflow-postgresql:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 5Gi

minio:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi

setupScript:
  # -- Image used to for setup scripts job
  image: bitnami/kubectl:latest
  clusterType: kind
