global: {}
deployment:
  # -- mlp image related configs
  image:
    pullPolicy: IfNotPresent
    registry: ghcr.io
    repository: gojek/mlp
    tag: v1.7.1

  replicaCount: 1

  # -- Additional labels to apply on the pod level
  podLabels: {}

  # -- Configure resource requests and limits, Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

  livenessProbe:
    path: "/v1/internal/live"
  readinessProbe:
    path: "/v1/internal/ready"

  apiHost: "http://mlp/v1"
  mlflowTrackingUrl: "http://mlflow.mlp"
  environment: "production"

  authorization:
    enabled: false
    serverUrl: http://mlp-authorization-keto

  # -- teams list
  teams:
    - marketing
    - operation
    - business

  # -- Streams list
  streams:
    - promotion-marketing
    - operation-strategy
    - business-analyst

  # -- Documentation list for caraml components, Added as part of env variables.
  docs:
    [
      {
        "label": "Merlin User Guide",
        "href": "https://github.com/gojek/merlin/blob/main/docs/getting-started/README.md",
      },
      {
        "label": "Turing User Guide",
        "href": "https://github.com/gojek/turing",
      },
      {
        "label": "Feast User Guide",
        "href": "https://docs.feast.dev/user-guide/overview",
      },
    ]

  ui:
    feastCoreApi: "http://feast.dev/v1"
    merlinApi: "http://merlin.dev/v1"
    turingApi: "http://turing.dev/v1"
    clockworkHomepage: "http://clockwork.dev"
    feastHomepage: "http://feast.dev"
    kubeflowHomepage: "http://kubeflow.org"
    merlinHomepage: "http://merlin.dev"
    turingHomepage: "http://turing.dev"

  # -- OAuth client id for login
  oauthClientID: ""

ingress:
  enabled: false
  # class:
  # host:
  # path: "/"

encryption:
  # encryption.key must be specified using --set flag.
  key: "example-key-here"

service:
  externalPort: 8080
  internalPort: 8080

externalPostgresql:
  # -- If you would like to use an external postgres database, enable it here using this
  enabled: false
  # -- External postgres database user
  username: mlp
  # -- External postgres database schema
  database: mlp
  # -- Set the External postgres db password using this value at runtime (using --set flag) to create a secret
  password: password
  # -- Host address for the External postgres
  address: 127.0.0.1
  # -- If a secret is created by external systems (eg. Valut)., mention the secret name here
  secretName: ""
# -- If a secret is created by external systems (eg. Valut)., mention the key under which password is stored in secret (eg. postgresql-password)
  secretKey: ""

postgresql:
  # -- Enable creating mlp specific postgres instance
  enabled: true

  # -- Configure resource requests and limits, Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

  persistence:
    size: 10Gi

  # -- override the name here so that db gets created like <release_name>-mlp-postgresql
  nameOverride: mlp-postgresql

  postgresqlUsername: mlp
  postgresqlDatabase: mlp
  # metrics:
  #   enabled: true
  #   serviceMonitor:
  #     enabled: true
  # replication:
  #   enabled: true
  #   user: repl_user
  #   password: repl_password
  #   slaveReplicas: 2
  #   ## Set synchronous commit mode: on, off, remote_apply, remote_write and local
  #   ## ref: https://www.postgresql.org/docs/9.6/runtime-config-wal.html#GUC-WAL-LEVEL
  #   synchronousCommit: "on"
  #   ## From the number of `slaveReplicas` defined above, set the number of those that will have synchronous replication
  #   ## NOTE: It cannot be > slaveReplicas
  #   numSynchronousReplicas: 2
  #   ## Replication Cluster application name. Useful for defining multiple replication policies
  #   applicationName: mlp
