apiVersion: v1
kind: Secret
metadata:
  name: {{ template "observation-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observation-svc.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- toYaml .Values.observationService.apiConfig | nindent 4 -}}
