{{- if .Values.observationService.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "observation-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "observation-svc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "observation-svc.name" .}}
      release: {{ .Release.Name }}
  endpoints:
    - port: http
      path: {{ .Values.observationService.monitoring.baseURL }}
{{- end }}
