{{- if and .Values.imageBuilder.serviceAccount .Values.imageBuilder.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "merlin.kaniko-sa" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.imageBuilder.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.imageBuilder.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
    {{- if .Values.imageBuilder.serviceAccount.labels }}
    {{- toYaml .Values.imageBuilder.serviceAccount.labels | nindent 4 }}
    {{- end }}
{{ end }}
