apiVersion: v1
kind: Secret
metadata:
  name: {{ template "merlin.mlp-api-encryption-key-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryption-key: {{ .Values.mlpApi.encryptionKey }}
