{{- if and .Values.merlinExternalPostgresql.enabled .Values.merlinExternalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.postgres-password-secret-name" (list (index .Values "merlin-postgresql") .Values.merlinExternalPostgresql .Release .Chart ) | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "common.postgres-password-secret-key" (list .Values.merlinExternalPostgresql) }}: {{ .Values.merlinExternalPostgresql.password }}
{{- end }}
