{{- if (index .Values "merlin-postgresql" "useExternalPostgresql") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "merlin-postgresql.password-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ index .Values "merlin-postgresql" "postgresqlPassword" }}
{{- end }}
