{{- $globReactAppHomepage := include "common.get-component-value" (list .Values.global "merlin" (list "uiPrefix"))}}
{{- $globMerlinApi := include "common.get-component-value" (list .Values.global "merlin" (list "vsPrefix" "apiPrefix"))}}
{{- $globMlpApi := include "common.get-component-value" (list .Values.global "mlp" (list "vsPrefix" "apiPrefix"))}}
{{- $globMlpApiHost := include "merlin.get-workload-host" (list .Values.global .Release.Namespace "mlp")}}
{{- $globOauthClientID := include "common.get-oauth-client" .Values.global }}
{{- $globFeastApiHost := include "merlin.get-feast-api-host" .Values.global }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "merlin.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
    {{- if .Values.deployment.labels }}
      {{- toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "merlin.name" .}}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "merlin.name" .}}
        release: {{ .Release.Name }}
        {{- if .Values.deployment.podLabels }}
          {{- toYaml .Values.deployment.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "{{ .Values.service.internalPort }}"
    spec:
      containers:
      - name: merlin
        image: "{{- if .Values.deployment.image.registry -}}{{ .Values.deployment.image.registry }}/{{- end -}}{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /v1/internal/live
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/internal/ready
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
        env:
          - name: ENVIRONMENT
            value: "{{ .Values.environment }}"
          - name: LOGGER_DESTINATION_URL
            value: "{{ .Values.loggerDestinationURL }}"
          - name: NUM_OF_WORKERS
            value: "{{ .Values.queue.numOfWorkers }}"
          - name: PORT
            value: "{{ .Values.service.internalPort }}"
          - name: DATABASE_HOST
            value: {{ include "common.postgres-host" (list (index .Values "merlin-postgresql") .Values.merlinExternalPostgresql .Release .Chart ) }}
          - name: DATABASE_USER
            value: {{ include "common.postgres-username" (list (index .Values "merlin-postgresql") .Values.merlinExternalPostgresql .Values.global ) }}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "common.postgres-password-secret-name" (list (index .Values "merlin-postgresql") .Values.merlinExternalPostgresql .Release .Chart ) }}
                key: {{ include "common.postgres-password-secret-key" (list .Values.merlinExternalPostgresql) }}
          - name: DATABASE_NAME
            value: {{ include "common.postgres-database" (list (index .Values "merlin-postgresql") .Values.merlinExternalPostgresql .Values.global "merlin" "postgresqlDatabase") }}
          - name: REACT_APP_OAUTH_CLIENT_ID
            value: {{ include "common.set-value" (list .Values.ui.oauthClientID $globOauthClientID) | quote }}
          - name: REACT_APP_ENVIRONMENT
            value: "{{ .Values.environment }}"
          {{- if .Values.sentry.enabled }}
          - name: REACT_APP_SENTRY_DSN
            value: "{{ .Values.sentry.dsn }}"
          {{- end }}
          {{- if .Values.ui.docsURL }}
          - name: REACT_APP_MERLIN_DOCS_URL
            value: {{ .Values.ui.docsURL | toJson | quote }}
          {{- end }}
          - name: REACT_APP_HOMEPAGE
            value: {{ include "common.set-value" (list .Values.ui.homepage $globReactAppHomepage) | quote }}
          - name: REACT_APP_MERLIN_API
            value: {{ include "common.set-value" (list .Values.ui.apiHost $globMerlinApi) | quote }}
          - name: REACT_APP_MLP_API
            value: {{ include "common.set-value" (list .Values.ui.mlp.apiHost $globMlpApi) | quote }}
          - name: REACT_APP_FEAST_CORE_API
            value: {{ include "common.set-value" (list .Values.feastCoreApi.apiHost $globFeastApiHost) }}
          - name: REACT_APP_DOCKER_REGISTRIES
            value: "{{ .Values.ui.dockerRegistries }}"
          - name: REACT_APP_MAX_ALLOWED_REPLICA
            value: "{{ .Values.ui.maxAllowedReplica }}"
          - name: IMG_BUILDER_CLUSTER_NAME
            value: "{{ .Values.imageBuilder.clusterName }}"
          - name: IMG_BUILDER_BASE_IMAGES
            value: {{ .Values.imageBuilder.baseImages | toJson | quote }}
          - name: IMG_BUILDER_PREDICTION_JOB_BASE_IMAGES
            value: {{ .Values.imageBuilder.predictionJobBaseImages | toJson | quote }}
          - name: IMG_BUILDER_NAMESPACE
            value: "{{ .Values.imageBuilder.namespace }}"
          - name: IMG_BUILDER_DOCKER_REGISTRY
            value: "{{ .Values.imageBuilder.dockerRegistry }}"
          - name: IMG_BUILDER_TIMEOUT
            value: "{{ .Values.imageBuilder.timeout }}"
          - name: IMG_BUILDER_KANIKO_IMAGE
            value: "{{ .Values.imageBuilder.kanikoImage }}"
          - name: IMG_BUILDER_TOLERATIONS
            value: {{ .Values.imageBuilder.tolerations | toJson | quote }}
          - name: IMG_BUILDER_NODE_SELECTORS
            value: {{ .Values.imageBuilder.nodeSelectors | toJson | quote }}
          - name: IMG_BUILDER_MAX_RETRY
            value: "{{ .Values.imageBuilder.maxRetry }}"
          {{- if .Values.imageBuilder.contextSubPath }}
          - name: IMG_BUILDER_CONTEXT_SUB_PATH
            value: "{{ .Values.imageBuilder.contextSubPath }}"
          {{- end }}
          {{- if .Values.imageBuilder.predictionJobContextSubPath }}
          - name: IMG_BUILDER_PREDICTION_JOB_CONTEXT_SUB_PATH
            value: "{{ .Values.imageBuilder.predictionJobContextSubPath }}"
          {{- end }}
          - name: IMG_BUILDER_RETENTION
            value: "{{ .Values.imageBuilder.retention }}"
          - name: DEFAULT_FEAST_SERVING_URL
            value: "{{ .Values.transformer.feast.defaultServingURL }}"
          - name: FEAST_SERVING_URLS
            value: {{ .Values.transformer.feast.servingURLs | toJson | quote }}
          {{- if .Values.transformer.feast.redisStorage }}
          - name: FEAST_REDIS_CONFIG
            value: {{ .Values.transformer.feast.redisStorage | toJson | quote }}
          {{- end }}
          {{- if .Values.transformer.feast.bigtableStorage }}
          - name: FEAST_BIG_TABLE_CONFIG
            value: {{ .Values.transformer.feast.bigtableStorage | toJson | quote }}
          {{- end }}
          - name: FEAST_BIGTABLE_CREDENTIAL
            value: {{ .Values.transformer.feast.bigtableCredential}}
          - name: DEFAULT_FEAST_SOURCE
            value: {{ .Values.transformer.feast.defaultFeastSource}}
          - name: SIMULATION_FEAST_REDIS_URL
            value: {{ .Values.transformer.simulation.feastRedisServingURL}}
          - name: SIMULATION_FEAST_BIGTABLE_URL
            value: {{ .Values.transformer.simulation.feastBigtableServingURL}}
          - name: FEAST_CORE_URL
            value: "{{ .Values.transformer.feast.coreURL }}"
          - name: FEAST_CORE_AUTH_AUDIENCE
            value: "{{ .Values.transformer.feast.coreAuthAudience }}"
          - name: FEAST_AUTH_ENABLED
            value: "{{ .Values.transformer.feast.authEnabled }}"
          - name: STANDARD_TRANSFORMER_IMAGE_NAME
            value: "{{ .Values.transformer.image }}"
          - name: JAEGER_AGENT_HOST
            value: "{{ .Values.transformer.jaeger.agentHost }}"
          - name: JAEGER_AGENT_PORT
            value: "{{ .Values.transformer.jaeger.agentPort }}"
          - name: JAEGER_SAMPLER_TYPE
            value: "{{ .Values.transformer.jaeger.samplerType }}"
          - name: JAEGER_SAMPLER_PARAM
            value: "{{ .Values.transformer.jaeger.samplerParam }}"
          - name: JAEGER_DISABLED
            value: "{{ .Values.transformer.jaeger.disabled }}"
          - name: VAULT_ADDRESS
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.vault.secretName }}"
                key: address
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.vault.secretName }}"
                key: token
          - name: DEPLOYMENT_CONFIG_PATH
            value: "/opt/config/environment.yaml"
          {{ if .Values.sentry.enabled }}
          - name: SENTRY_ENABLED
            value: "{{ .Values.sentry.enabled }}"
          - name: SENTRY_DSN
            value: "{{ .Values.sentry.dsn }}"
          {{- end }}
          - name: NEWRELIC_ENABLED
            value: "{{ .Values.newrelic.enabled }}"
          {{- if .Values.newrelic.enabled }}
          - name: NEWRELIC_APPNAME
            value: "{{ .Values.newrelic.appname }}"
          - name: NEWRELIC_LICENSE
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.newrelic.licenseSecretName }}"
                key: key
          - name: NEWRELIC_IGNORESTATUSCODES
            value: "400,401,403,404,405,412"
          {{- end }}
          - name: AUTHORIZATION_ENABLED
            value: "{{ .Values.authorization.enabled }}"
          {{- if .Values.authorization.enabled }}
          - name: AUTHORIZATION_SERVER_URL
            value: {{ include "merlin.authorization.server.url" . | quote }}
          {{- end }}
          - name: MONITORING_DASHBOARD_ENABLED
            value: "{{ .Values.monitoring.enabled }}"
          {{- if .Values.monitoring.enabled }}
          - name: MONITORING_DASHBOARD_BASE_URL
            value: "{{ .Values.monitoring.baseURL }}"
          - name: MONITORING_DASHBOARD_JOB_BASE_URL
            value: "{{ .Values.monitoring.jobBaseURL }}"
          {{- end }}
          - name: ALERT_ENABLED
            value: "{{ .Values.alerts.enabled }}"
          {{- if .Values.alerts.enabled }}
          - name: GITLAB_BASE_URL
            value: "{{ .Values.alerts.baseURL }}"
          - name: GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ template "merlin.alerts-repo-secret-name" . }}"
                key: "{{ template "merlin.alerts-repo-secret-key-name" . }}"
          - name: GITLAB_DASHBOARD_REPOSITORY
            value: "{{ .Values.alerts.dashboardRepository }}"
          - name: GITLAB_DASHBOARD_BRANCH
            value: "{{ .Values.alerts.dashboardBranch }}"
          - name: GITLAB_ALERT_REPOSITORY
            value: "{{ .Values.alerts.alertRepository }}"
          - name: GITLAB_ALERT_BRANCH
            value: "{{ .Values.alerts.alertBranch }}"
          - name: WARDEN_API_HOST
            value: "{{ .Values.alerts.warden.apiHost }}"
          {{- end }}
          - name: MLP_API_HOST
            value: {{ include "common.set-value" (list .Values.mlpApi.apiHost $globMlpApiHost) }}
          - name: MLP_API_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ template "merlin.mlp-api-encryption-key-name" . }}"
                key: encryption-key
          - name: MLFLOW_TRACKING_URL
            value: "{{ .Values.mlflow.trackingURL }}"
          {{- if .Values.gcpServiceAccount }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/gcp_service_account/service-account.json
          {{- end }}
        volumeMounts:
        - mountPath: /opt/config
          name: config
        {{- if .Values.gcpServiceAccount }}
        - name: gcp-service-account
          mountPath: "/etc/gcp_service_account"
          readOnly: true
        {{- end }}

      {{- if .Values.swagger.enabled }}
      - name: swagger-ui
        image: "swaggerapi/swagger-ui:{{ .Values.swagger.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.swagger.service.internalPort }}
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
          - name: LAYOUT
            value: "BaseLayout"
          - name: SWAGGER_JSON
            value: "/app/swagger.yaml"
          - name: PORT
            value: "{{ .Values.swagger.service.internalPort }}"
          - name: API_HOST
            value: "{{ .Values.swagger.apiHost }}"
          - name: BASE_PATH
            value: "{{ .Values.swagger.basePath }}"
        command: ['sh', '-c']
        args:
          - |
            mkdir /app
            echo "Fetching swagger configuration from http://127.0.0.1:{{ .Values.service.internalPort }}/swagger.yaml..."
            until $$(wget -O $${SWAGGER_JSON} --tries 1 --timeout 1 http://127.0.0.1:{{ .Values.service.internalPort }}/swagger.yaml); do
              printf '.'
              sleep 10
            done
            echo "Update Swagger config..."
            sed -r -i 's/^(\s*)(host\s*:.*$$)/\host: "'$${API_HOST}'"/' $${SWAGGER_JSON}
            sed -r -i 's#^(\s*)(basePath\s*:.*$$)#\basePath: "'$${BASE_PATH}'"#' $${SWAGGER_JSON}
            echo "Running Swagger UI..."
            /usr/share/nginx/run.sh
      {{- end }}

      volumes:
      - name: config
        configMap:
          name: {{ template "merlin.envs-cm-name" .}}
      {{- if .Values.gcpServiceAccount }}
      - name: gcp-service-account
        secret:
          secretName: {{ .Values.gcpServiceAccount.secretName }}
          items:
            - key: {{ .Values.gcpServiceAccount.secretKey }}
              path: service-account.json
      {{- end }}

{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
{{- end }}

{{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
{{- end }}
