apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "merlin.envs-cm-name" .}}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
data:
  environment.yaml: |-
{{- if .Values.environmentConfigs }}
{{ toYaml .Values.environmentConfigs | indent 4 }}
{{- end }}
