# Secret is created only if mlp envconfig secret not set
{{- if not .Values.mlp.environmentConfigSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "merlin.fullname" .}}-environments
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
stringData:
  {{ .Values.config.EnvironmentConfigPath }}: |
    {{- include "merlin.environments" . | nindent 4 -}}
{{- end }}
