# Secret is created only if mlp envconfig secret not set
{{- if not .Values.mlp.environmentConfigSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "merlin.fullname" .}}-environments
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
stringData:
  environment.yaml: |-
{{- if .Values.environmentConfigs }}
{{ toYaml .Values.environmentConfigs | indent 4 }}
{{- end }}
  imageBuilderK8sConfig: |-
{{- if .Values.imageBuilder.k8sConfig }}
{{ .Values.imageBuilder.k8sConfig | indent 4 }}
{{- end }}
{{- end }}
