apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "merlin.fullname" . }}-config
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- include "merlin.config" . | nindent 4 -}}
