{{- if or .Values.clusterConfig.useInClusterConfig .Values.serviceAccount.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "merlin.serviceAccountName" . }}-role-binding
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "merlin.serviceAccountName" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ template "merlin.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
