{{- if .Values.config.FeatureToggleConfig.AlertConfig.AlertEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "merlin.alerts-repo-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ template "merlin.alerts-repo-secret-key-name" . }}: {{ .Values.config.FeatureToggleConfig.AlertConfig.GitlabConfig.Token }}
{{- end }}
