{{- if or .Values.clusterConfig.useInClusterConfig .Values.serviceAccount.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "merlin.serviceAccountName" . }}-cluster-role
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups: [""]
  resources:
  - services
  - pods
  - pods/log
  - namespaces
  - configmaps
  - secrets
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - "*"
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  - predictors
  verbs:
  - "*"
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - "*"
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  verbs:
  - "*"
{{- end }}
