{{- $globServiceName := include "common.get-component-value" (list .Values.global "merlin" (list "serviceName")) }}
{{- $globServicePort := include "common.get-component-value" (list .Values.global "merlin" (list "externalPort")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.set-value" (list (include "merlin.fullname" .) $globServiceName) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ include "common.set-value" (list (.Values.service.externalPort | toString) $globServicePort) | atoi }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "merlin.name" .}}
    release: {{ .Release.Name }}
