{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ default "merlin" .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
    {{- if .Values.serviceAccount.annotations }}
    annotations:
      {{- toYaml .Values.serviceAccount.annotations | nindent 6 }}
    {{ end }}
    labels:
      {{- include "merlin.labels" . | nindent 6 }}
{{ end }}
