apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
    {{- if .Values.mlflow.deploymentLabels}}
      {{- toYaml .Values.mlflow.deploymentLabels | nindent 4 }}
    {{- end}}
spec:
  replicas: {{ .Values.mlflow.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mlflow.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.mlflow.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.mlflow.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ template "mlflow.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.mlflow.podLabels }}
          {{- toYaml .Values.mlflow.podLabels | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ template "mlflow.fullname" . }}
        image: "{{- if .Values.mlflow.image.registry -}}{{ .Values.mlflow.image.registry }}/{{- end -}}{{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}"
        imagePullPolicy: {{ .Values.mlflow.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mlflow.service.internalPort }}
          name: "http"
        livenessProbe:
          httpGet:
            path: {{ default "/api/2.0/mlflow/experiments/list" .Values.mlflow.livenessProbe.path }}
            port: {{ .Values.mlflow.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.mlflow.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mlflow.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.mlflow.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.mlflow.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ default "/api/2.0/mlflow/experiments/list" .Values.mlflow.readinessProbe.path }}
            port: {{ .Values.mlflow.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.mlflow.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mlflow.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.mlflow.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.mlflow.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.mlflow.resources | indent 10 }}
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ template "mlflow-postgresql.password-secret-name" . }}"
              key: "{{ template "mlflow-postgresql.password-secret-key" . }}"
        - name: BACKEND_STORE_URI
          value: "{{ template "mlflow.backendStoreUri" . }}"
        - name: ARTIFACT_ROOT
          value: "{{ .Values.mlflow.artifactRoot }}"
        - name: HOST
          value: "{{ .Values.mlflow.host }}"
        - name: PORT
          value: "{{ .Values.mlflow.service.internalPort }}"
        {{- if .Values.minio.enabled }}
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.minio.svc.cluster.local:9000
        {{- end}}
        {{- range $key, $val := .Values.mlflow.extraEnvs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end}}
        {{- if .Values.gcpServiceAccount }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp_service_account/service-account.json
        {{- end }}

        {{- if .Values.gcpServiceAccount }}
        volumeMounts:
        - name: gcp-service-account
          mountPath: "/etc/gcp_service_account"
          readOnly: true
        {{- end }}
{{- if .Values.mlflow.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.mlflow.imagePullSecrets | indent 6 }}
{{- end }}

{{- if .Values.mlflow.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.mlflow.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.gcpServiceAccount }}
      volumes:
      - name: gcp-service-account
        secret:
          secretName: {{ .Values.gcpServiceAccount.secretName }}
          items:
            - key: {{ .Values.gcpServiceAccount.secretKey }}
              path: service-account.json
{{- end }}
{{- with .Values.mlflow.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
