{{- $globServiceName := include "common.get-component-value" (list .Values.global "mlflow" (list "serviceName")) }}
{{- $globServicePort := include "common.get-component-value" (list .Values.global "mlflow" (list "externalPort")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.set-value" (list (include "mlflow.fullname" .) $globServiceName) }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.mlflow.service.annotations }}
  annotations:
{{ toYaml .Values.mlflow.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "mlflow.fullname" . }}
    {{- include "merlin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mlflow.service.type }}
{{- if .Values.mlflow.service.clusterIP }}
  clusterIP: {{ .Values.mlflow.service.clusterIP }}
{{- end }}
{{- if .Values.mlflow.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.mlflow.service.loadBalancerIP }}
{{- end }}
{{- /*
  Customizing loadBalancerSourceRanges, following the approach from
  https://github.com/helm/charts/blob/master/incubator/haproxy-ingress
*/ -}}
{{- if .Values.mlflow.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.mlflow.service.loadBalancerSourceRanges | indent 2 }}
{{- end }}
  ports:
  - port: {{ include "common.set-value" (list .Values.mlflow.service.externalPort $globServicePort)  }}
    targetPort: {{ .Values.mlflow.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "mlflow.fullname" . }}
    release: {{ .Release.Name }}
