{{- if and .Values.mlflow.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ default "mlflow" .Values.mlflow.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
    {{- if and .Values.mlflow.serviceAccount.annotations }}
    annotations:
      {{- toYaml .Values.mlflow.serviceAccount.annotations | nindent 6 }}
    {{ end }}
    labels:
      {{- include "merlin.labels" . | nindent 6 }}
{{ end }}
