{{- if and .Values.mlflowExternalPostgresql.enabled .Values.mlflowExternalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow-postgresql.password-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ template "mlflow-postgresql.password-secret-key" . }}: {{ .Values.mlflowExternalPostgresql.password }}
{{- end }}
