---
# Create a vault secret for quick install. For a production use case never use the vault server in dev mode.
{{ if and .Values.setupScript.enabled .Values.vault.chartValues.server.dev.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  address: "http://vault.vault.svc:8200"
  token: root
{{ end }}
