{{- if .Values.setupScript.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-setup-role" (include "merlin.resource-prefix" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["delete", "get"]

---
{{- $serviceAccountName := printf "%s-setup-sa" (include "merlin.resource-prefix" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-setup-crb" (include "merlin.resource-prefix" .) }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-setup-role" (include "merlin.resource-prefix" .) }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
