{{/* {{- if .Values.setupScript.enabled }} */}}
{{/* --- */}}
{{/* {{- $serviceAccountName := printf "%s-setup-sa" (include "merlin.resource-prefix" .) }} */}}
{{/* apiVersion: v1 */}}
{{/* kind: ServiceAccount */}}
{{/* metadata: */}}
{{/*   name: {{ $serviceAccountName }} */}}
{{/*   namespace: {{ .Release.Namespace }} */}}
{{/*   labels: */}}
{{/*     {{- include "merlin.labels" . | nindent 4 }} */}}
{{/* {{- end }} */}}
