---
# Create a vault secret for quick install. For a production use case never use the vault server in dev mode.
{{ if .Values.vault.server.dev.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "merlin.labels" . | nindent 4 }}
type: Opaque
stringData:
  address: {{ printf "http://%s-vault.%s.svc:8200" .Release.Name .Release.Namespace }}
  token: root
{{ end }}
