---
{{- $serviceAccountName := printf "%s-setup-sa" (include "merlin.resource-prefix" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": "hook-failed,before-hook-creation"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-3"
