config:
  istio:
    # NOTE: assumes istio edge proxies (*-gateway deployments) are deployed in istio-system-knative-serving-istio namespace
    gateway.{{ .Release.Namespace }}.knative-ingress-gateway: "istio-ingressgateway.istio-system-knative-serving-istio.svc.cluster.local"
    local-gateway.{{ .Release.Namespace }}.knative-local-gateway: "cluster-local-gateway.istio-system-knative-serving-istio.svc.cluster.local"

controller:
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 512Mi

webhook:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 500Mi

knativeServingCore:
  activator:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 250m
        memory: 500Mi

  autoscaler:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 250m
        memory: 500Mi

  controller:
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        cpu: 250m
        memory: 500Mi

  domainMapping:
    resources:
      requests:
        cpu: 30m
        memory: 40Mi
      limits:
        cpu: 50m
        memory: 100Mi

  domainMappingWebhook:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 500Mi

  webhook:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 500Mi

  autoscalerHpa:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 500Mi

base:
  global:
    istioNamespace: "istio-system-knative-serving-istio"


istiod:
  helmChart:
    namespace: "istio-system-knative-serving-istio"
  chartValues:
    global:
      istioNamespace: "istio-system-knative-serving-istio"
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 1024Mi

istioIngressGateway:
  helmChart:
    namespace: "istio-system-knative-serving-istio"
  chartValues:
    global:
      istioNamespace: "istio-system-knative-serving-istio"
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 512Mi

clusterLocalGateway:
  helmChart:
    namespace: "istio-system-knative-serving-istio"
  chartValues:
    global:
      istioNamespace: "istio-system-knative-serving-istio"
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 200m
        memory: 512Mi
