{{- if not .Values.mlp.environmentConfigSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "turing.fullname" . }}-environments
  labels:
    {{- include "turing.labels" . | nindent 4 }}
stringData:
  {{ .Values.clusterConfig.environmentConfigPath }}: |
    {{- include "turing.environments" . | nindent 4 -}}
{{- end }}
