{{- $globServiceName := include "common.get-component-value" (list .Values.global "turing" (list "serviceName")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.set-value" (list (include "turing.fullname" .) $globServiceName) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "turing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "turing.name" . }}
    release: {{ .Release.Name }}
