apiVersion: v1
kind: Service
metadata:
  name: {{ template "turing.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "turing.fullname" . }}
    chart: {{ template "turing.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ if .Values.deployment.labels -}}
{{ toYaml .Values.deployment.labels | indent 4 -}}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "turing.fullname" . }}
    release: {{ .Release.Name }}
