{{- if or .Values.serviceAccount.create .Values.clusterConfig.useInClusterConfig -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "turing.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  labels:
    {{- include "turing.labels" . | nindent 4 }}
{{- end }}
