{{- if and .Values.turingExternalPostgresql.enabled .Values.turingExternalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.postgres-password-secret-name" (list (index .Values "turing-postgresql") .Values.turingExternalPostgresql .Release .Chart ) | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "turing.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "common.postgres-password-secret-key" (list .Values.turingExternalPostgresql) }}: {{ .Values.turingExternalPostgresql.password }}
{{- end }}
