---
{{- if and (or .Values.istioIngressGateway.global.enabled .Values.clusterLocalGateway.global.enabled) .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats-metrics-monitor
  namespace: {{ .Values.monitoring.istioSystemNS }}
  labels:
{{ include "knative-net-istio.labels" . | indent 4 }}
spec:
{{- if .Values.monitoring.istioEnvoy.selector }}
  selector:
{{ toYaml .Values.monitoring.istioEnvoy.selector | indent 4 }}
{{- end }}
{{- if .Values.monitoring.istioEnvoy.namespaceSelector }}
  namespaceSelector:
{{ toYaml .Values.monitoring.istioEnvoy.namespaceSelector | indent 4 }}
{{- end }}
  podMetricsEndpoints:
{{ toYaml .Values.monitoring.istioEnvoy.envoyStats | indent 4 }}
{{- end }}
