{{- if and .Values.caramlAuthzExternalPostgresql.enabled .Values.caramlAuthzExternalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.postgres-password-secret-name" (list (index .Values "caraml-authz-postgresql") .Values.caramlAuthzExternalPostgresql .Release .Chart ) | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caraml-authz.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "common.postgres-password-secret-key" (list .Values.caramlAuthzExternalPostgresql) }}: {{ .Values.caramlAuthzExternalPostgresql.password }}
{{- end -}}
