{{- if and .Values.caramlAuthzExternalPostgresql.enabled .Values.caramlAuthzExternalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "caraml-authz-postgresql.password-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "caraml-authz.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ template "caraml-authz-postgres.password-secret-key" . }}: {{ .Values.caramlAuthzExternalPostgresql.password }}
{{- end -}}
