apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "caraml-authz.fullname" . }}
  labels:
    {{- include "caraml-authz.labels" . | nindent 4 }}
    {{- with .Values.deployment.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "caraml-authz.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "caraml-authz.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: {{ template "caraml-authz.resource-prefix" . }}-migration
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        args: ["migrate", "sql", "-e"]
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.postgres-password-secret-name" (list (index .Values "caraml-authz-postgresql") .Values.caramlAuthzExternalPostgresql .Release .Chart ) | quote }}
              key: {{ include "common.postgres-password-secret-key" (list .Values.caramlAuthzExternalPostgresql (default "password" .Values.global.dbSecretKey)) | quote }}
        - name: DATABASE_HOST
          value: {{ include "common.postgres-host" (list (index .Values "caraml-authz-postgresql") .Values.caramlAuthzExternalPostgresql .Release .Chart ) }}
        - name: DSN
          value: {{ template "caraml-authz.postgresql.dsn" . }}
        resources:
{{- toYaml .Values.deployment.initResources | nindent 10 }}
      containers:
      - name: {{ template "caraml-authz.resource-prefix" . }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 4466
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health/alive
            port: http
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.postgres-password-secret-name" (list (index .Values "caraml-authz-postgresql") .Values.caramlAuthzExternalPostgresql .Release .Chart ) | quote }}
              key: {{ include "common.postgres-password-secret-key" (list .Values.caramlAuthzExternalPostgresql (default "password" .Values.global.dbSecretKey)) | quote }}
        - name: DATABASE_HOST
          value: {{ include "common.postgres-host" (list (index .Values "caraml-authz-postgresql") .Values.caramlAuthzExternalPostgresql .Release .Chart ) }}
        - name: DSN
          value: {{ template "caraml-authz.postgresql.dsn" . }}
        resources:
{{- toYaml .Values.deployment.resources | nindent 10 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ default "caraml-authz" .Values.serviceAccount.name }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
