apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "caraml-store.registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "caraml-store.registry.labels" . | indent 4 }}
data:
{{- if index .Values.registry "application-generated.yaml" "enabled" }}
  application-generated.yaml: |

    {{- if index .Values "postgresql" "enabled" }}
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/postgres
    {{- end }}
    server:
      port: {{ .Values.registry.actuator.port }}
    kubernetes:
      inCluster: true
    jobService:
      common:
        sparkImage: "ghcr.io/caraml-dev/caraml-store-spark:{{ .Values.registry.image.tag | default .Chart.AppVersion }}"
{{- end }}

{{- if index .Values.registry "application-override.yaml" "enabled" }}
  application-override.yaml: |
{{- toYaml (index .Values.registry "application-override.yaml") | nindent 4 }}
{{- end }}