apiVersion: v1
kind: Service
metadata:
  name: {{ include "caraml-store.registry.fullname" . }}
  labels:
    {{- include "caraml-store.registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.registry.service.grpc.port }}
      targetPort: {{ .Values.registry.service.grpc.targetPort }}
    {{- if .Values.registry.service.grpc.nodePort }}
      nodePort: {{ .Values.registry.service.grpc.nodePort }}
    {{- end }}
  selector:
    {{- include "caraml-store.registry.selectorLabels" . | nindent 4 }}
