{{- if and .Values.registry.enabled .Values.registry.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "caraml-store.registry.fullname" . }}
  labels:
{{ include "caraml-store.registry.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{- include "caraml-store.registry.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: /actuator/prometheus
      targetPort: {{ .Values.registry.actuator.port }}
{{- end }}
