{{- if .Values.observationService.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "observation-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observation-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "observation-service.fullname" . }}
  minReplicas: {{ .Values.observationService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.observationService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.observationService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.observationService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
