apiVersion: v1
kind: Secret
metadata:
  name: {{ template "observation-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observation-service.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- toYaml .Values.observationService.apiConfig | nindent 4 -}}
