{{- if .Values.observationService.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "observation-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "observation-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "observation-service.name" .}}
      release: {{ .Release.Name }}
  endpoints:
    - targetPort: {{ .Values.observationService.service.internalPort }}
{{- end }}
