{{- if and .Values.xpManagementExternalPostgresql.enabled .Values.xpManagementExternalPostgresql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.postgres-password-secret-name" (list (index .Values "xp-management-postgresql") .Values.xpManagementExternalPostgresql .Release .Chart ) | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "management-svc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "common.postgres-password-secret-key" (list .Values.xpManagementExternalPostgresql) }}: {{ .Values.xpManagementExternalPostgresql.password }}
{{- end }}
