apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "management-svc.fullname" .}}-api-config
stringData:
  config.yaml: |
    {{- include "management-svc.config" . | nindent 4 -}}
  {{- if .Values.uiConfig }}
  ui.config.json: |
    {{- include "management-svc.ui.config" . | nindent 4 -}}
  {{- end }}
