apiVersion: v2
appVersion: v1.3.0
dependencies:
- alias: knativeServingCore
  condition: knativeServingCore.enabled
  name: knative-serving-core
  repository: https://caraml-dev.github.io/helm-charts
  version: 1.3.2
- alias: istiod
  condition: istiod.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.1
- alias: base
  condition: base.enabled
  name: base
  repository: https://istio-release.storage.googleapis.com/charts
  version: 1.13.9
- alias: istioIngressGateway
  condition: istioIngressGateway.global.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.1
- alias: clusterLocalGateway
  condition: clusterLocalGateway.global.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.1
description: Installs Knative-serving for Istio
maintainers:
- email: caraml-dev@caraml.dev
  name: caraml-dev
name: knative-serving-istio
type: application
version: 1.3.9
