apiVersion: v2
name: knative-serving-istio
description: Installs Knative-serving for Istio
type: application
version: 1.0.1
appVersion: "v1.0.0"
maintainers:
  - name: caraml-dev
    email: caraml-dev@caraml.dev
dependencies:
  - name: knative-serving-core
    # TODO: Replace with caraml-dev url once chart is released
    repository: "file://../knative-serving-core"
    version: 1.1.0
    alias: knativeServingCore
    condition: knativeServingCore.enabled
  - name: generic-dep-installer
    # TODO: Replace with caraml-dev url once chart is released
    repository: "file://../helm-dep-installer"
    version: 0.1.0
    alias: istiod
    condition: istiod.enabled
  - name: base
    repository: "https://istio-release.storage.googleapis.com/charts"
    version: 1.13.4
    alias: base
    condition: base.enabled
  - name: generic-dep-installer
    # TODO: Replace with caraml-dev url once chart is released
    repository: "file://../helm-dep-installer"
    version: 0.1.0
    alias: istioIngressGateway
    condition: istioIngressGateway.global.enabled
  - name: generic-dep-installer
    # TODO: Replace with caraml-dev url once chart is released
    repository: "file://../helm-dep-installer"
    version: 0.1.0
    alias: clusterLocalGateway
    condition: clusterLocalGateway.global.enabled
