apiVersion: v2
description: "CaraML store registry: Feature registry for CaraML store."
name: caraml-store-registry
version: 0.1.0
appVersion: 0.1.1
home: https://github.com/caraml-dev/caraml-store
keywords:
- machine learning
- feature store
- big data
- mlops
maintainers:
  - name: caraml-dev
    email: caraml-dev@caraml.dev
dependencies:
  - name: postgresql
    version: 11.9.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
