apiVersion: v1
kind: Secret
metadata:
  name: {{ template "caraml-store.serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: registry
{{ include "caraml-store.serving.labels" . | indent 4 }}
type: Opaque
stringData:
  application-secret.yaml: |
{{- toYaml (index .Values "application-secret.yaml") | nindent 4  }}