{{- if and .Values.serving.enabled .Values.serving.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "caraml-store.serving.fullname" . }}
  labels:
{{ include "caraml-store.serving.labels" . | indent 4 }}
spec:
  selector:
{{- include "caraml-store.serving.selectorLabels" . | nindent 4 }}
  endpoints:
    - path: /actuator/prometheus
    - targetPort: {{ .Values.serving.actuator.port }}
{{- end }}
