apiVersion: v1
kind: Service
metadata:
  name: {{ template "caraml-store-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "caraml-store-registry.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 2 }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.service.http.targetPort }}
    {{- if .Values.service.http.nodePort }}
    nodePort: {{ .Values.service.http.nodePort }}
    {{- end }}
  - name: grpc
    port: {{ .Values.service.grpc.port }}
    targetPort: {{ .Values.service.grpc.targetPort }}
    {{- if .Values.service.grpc.nodePort }}
    nodePort: {{ .Values.service.grpc.nodePort }}
    {{- end }}
  selector:
    app: {{ template "caraml-store-registry.name" . }}
    component: registry
    release: {{ .Release.Name }}

