---
{{- $serviceAccountName := include "generic-dep-installer.sa-name"  . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed,before-hook-creation"
    "helm.sh/hook": "pre-install,pre-upgrade,post-delete"
    "helm.sh/hook-weight": {{ include "generic-dep-installer.sa-hook-value" . }}
