---
{{- $serviceAccountName := include "generic-dep-installer.sa-name"  . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed,before-hook-creation"
    "helm.sh/hook": "pre-install,pre-upgrade,post-delete"
    "helm.sh/hook-weight": {{ include "generic-dep-installer.sa-hook-value" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed,before-hook-creation"
    "helm.sh/hook": "pre-install,pre-upgrade,post-delete"
    "helm.sh/hook-weight": {{ include "generic-dep-installer.crb-hook-value" . }}
  name: {{ printf "%s-crb" (include "generic-dep-installer.global-resource-prefix" .) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ .Release.Namespace }}
