apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dap-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dap-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "dap-webhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: dap-secret-webhook
      labels:
        app: {{ include "dap-webhook.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ default (printf "%s" (include "dap-webhook.name" .)) .Values.serviceAccount.name }}
      containers:
        - name: app
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          env:
          {{- toYaml .Values.deployment.env | nindent 10 }}
          args:
          - webhook
          resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/tls-certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: dap-webhook-tls-certs