{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ default (printf "%s" (include "dap-webhook.name" .)) .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
    {{- if .Values.serviceAccount.annotations }}
    annotations:
      {{- toYaml .Values.serviceAccount.annotations | nindent 6 }}
    {{ end }}
    labels:
      {{- include "dap-webhook.labels" . | nindent 6 }}
{{ end }}
---

{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dap-webhook.name" . }}-cluster-role
  labels:
    {{- include "dap-webhook.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
      - mutatingwebhookconfigurations
    verbs:
      - get
      - create
      - update
      - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dap-webhook.name" . }}-role-binding
  labels:
    {{- include "dap-webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dap-webhook.name" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name:  {{ default (printf "%s" (include "dap-webhook.name" .)) .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
