{{- if .Values.gcpServiceAccount.credentialsData -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "timber-fluentd.fullname" . }}-secret
  labels:
    {{- include "timber-fluentd.labels" . | nindent 4 }}
data:
  service-account.json: |-
{{ .Values.gcpServiceAccount.credentialsData | indent 4 }}
{{- end }}
