apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fluentd
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-fluentd
    {{- include "timber-fluentd.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-fluentd
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.multiPort.enabled }}
  ports:
  {{- range .Values.service.multiPorts }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  {{ else }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  {{ end }}