{{- $ingressIP := include "common.istio-lookup" .Values.global }}
{{- if and .Values.https.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: caraml-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlp-tls-cert
  # NOTE: certificate secret needs to be in same namespace as istiod
  namespace: {{ .Values.global.istioLookUp.namespace }}
spec:
  secretName: {{ .Values.https.tls.credentialName }}
  issuerRef:
    name: caraml-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    {{- range .Values.mlpGateway.hosts }}
    - {{ include "common.localiseDomain" (list . $ingressIP $.Values.domain) }}
    {{- end }}
{{- end }}
