{{- $ingressIP := ternary .Values.global.ingressIP (include "common.istio-lookup" .Values.global) (ne .Values.global.ingressIP "") }}
{{- $hosts := (concat (get $.Values.global.hosts "mlp") (get $.Values.global.hosts "mlpdocs") (get $.Values.global.hosts "mlflow") )}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "caraml-routes.mlp-gateway" . }}
  namespace: {{ ternary .Release.Namespace .Values.namespace (ne .Values.namespace "") }}
  labels:
    {{- include "caraml-routes.labels" . | nindent 4 }}
spec:
{{- with .Values.mlpGateway }}
  selector:
    {{- toYaml .selector | nindent 6}}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range $hosts }}
        - {{ include "common.localiseDomain" (list . $ingressIP $.Values.global.domain) }}
        {{- end }}
{{- end }}
    {{- if .Values.https.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        {{- toYaml .Values.https.tls | nindent 8 }}
      hosts:
        {{- range $hosts }}
        - {{ include "common.localiseDomain" (list . $ingressIP $.Values.global.domain) }}
        {{- end }}
    {{- end }}
