{{- $ingressIP := ternary .Values.global.ingressIP (include "common.istio-lookup" .Values.global) (ne .Values.global.ingressIP "") }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" (include "caraml-routes.fullname" . ) "mlp-docs-vs" }}
  namespace: {{ ternary .Release.Namespace .Values.namespace (ne .Values.namespace "") }}
  labels:
    {{- include "caraml-routes.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.global.hosts.mlpdocs }}
    - {{ include "common.localiseDomain" (list . $ingressIP $.Values.global.domain ) }}
    {{- end}}
  gateways:
    - {{ include "caraml-routes.mlp-gateway" . }}
  http:
    # redirect all http to https
    {{- if .Values.https.enabled }}
    - name: "docs-http-to-https"
      match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    {{- end }}
    #########################################################
    #                  Merlin API Docs
    #########################################################
    {{- if .Values.merlin.enabled }}
    {{- with .Values.merlin.docs }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
    #########################################################
    #                   Turing API Docs
    #########################################################
    {{- if .Values.turing.enabled }}
    {{- with .Values.turing.docs }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
    #########################################################
    #              Turing Experiments API Docs
    #########################################################
    {{- if .Values.xp.enabled }}
    {{- with .Values.xp.managementDocs }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
    {{- with .Values.xp.treatmentDocs }}
    {{- if .enabled }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
