apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" (include "caraml-routes.fullname" . ) "mlp-docs-vs" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "caraml-routes.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.mlpDocs.vs.hosts }}
    - {{ include "caraml-routes.localiseDomain" (list . $.Values.istioIngressIP $.Values.domain ) }}
    {{- end}}
  gateways:
    - {{ include "caraml-routes.mlp-gateway" . }}
  http:
    # redirect all http to https
    {{- if .Values.https.enabled }}
    - name: "docs-http-to-https"
      match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    {{- end }}
    #########################################################
    #                  Merlin API Docs
    #########################################################
    {{- with .Values.mlpDocs.vs.merlin }}
    {{- if .enabled }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
    #########################################################
    #                   Turing API Docs
    #########################################################
    {{- with .Values.mlpDocs.vs.turing }}
    {{- if .enabled }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
    #########################################################
    #              Turing Experiments API Docs
    #########################################################
    {{- with .Values.mlpDocs.vs.xpManagement }}
    {{- if .enabled }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
    {{- with .Values.mlpDocs.vs.xpTreatment }}
    {{- if .enabled }}
    {{- include "caraml-routes.api-docs" (list .app .redirectMatch .rewriteUri .destHost .destPort) | indent 4}}
    {{- end }}
    {{- end }}
