{{- $ingressIP := include "caraml-routes.istio-lookup" . }}
{{- $s := include "common.store" . | fromJson }}
{{- $apps := $s.services}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" (include "caraml-routes.fullname" . ) "mlp-vs" }}
  namespace: {{ ternary .Release.Namespace .Values.namespace (ne .Values.namespace "") }}
  labels:
    {{- include "caraml-routes.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.mlp.vs.hosts }}
    - {{ include "common.localiseDomain" (list . $s.ingressIP $.Values.domain ) }}
    {{- end}}
  gateways:
    - {{ include "caraml-routes.mlp-gateway" . }}
  http:
    {{- if .Values.turing.enabled }}
    {{- with .Values.turing.api }}
    {{- include "caraml-routes.mlp-api-routes" (list .appName $apps.turing.vsPrefixMatch .rewriteUri $apps.turing.serviceName .authHeader) | indent 4}}
    {{- end }}
    {{- end }}
    {{- if .Values.xp.enabled }}
    {{- with .Values.xp.api }}
    {{- include "caraml-routes.mlp-api-routes" (list .appName $apps.xp.vsPrefixMatch .rewriteUri $apps.xp.serviceName .authHeader) | indent 4}}
    {{- end }}
    {{- end }}
    {{- if .Values.merlin.enabled }}
    {{- with .Values.merlin.api }}
    {{- include "caraml-routes.mlp-api-routes" (list .appName $apps.merlin.vsPrefixMatch .rewriteUri $apps.merlin.serviceName .authHeader) | indent 4}}
    {{- end }}
    {{- end }}
    {{- if .Values.mlp.enabled }}
    {{- with .Values.mlp.api }}
    {{- include "caraml-routes.mlp-api-routes" (list .appName $apps.mlp.vsPrefixMatch .rewriteUri $apps.mlp.serviceName .authHeader) | indent 4}}
    {{- end }}
    {{- end }}
    #########################################################
    #                       MLP API
    #########################################################
    {{- if .Values.feast.enabled }}
    {{- with .Values.feast.feastUIBackend }}
    - name: "feast-ui-backend"
      match:
        {{- toYaml .match | nindent 8}}
      rewrite:
        {{- toYaml .rewrite | nindent 8 }}
      route:
        {{- toYaml .route | nindent 8 }}
    {{- end }}
    {{- end }}
    #########################################################
    #                 MLP COMPONENTS UI
    #########################################################
    {{- if .Values.feast.enabled }}
    {{- with .Values.feast }}
    - name: "feast-ui-redirect"
      match:
        {{- toYaml .feastUIRedirect.match | nindent 8 }}
      redirect:
        uri: {{ .feastUIRedirect.redirect }}
    - name: "feast-ui"
      match:
        {{- toYaml .feastUI.match | nindent 8 }}
      route:
        {{- toYaml .feastUI.route | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.merlin.enabled }}
    {{- with .Values.merlin }}
    - name: "merlin-ui"
      match:
        - uri:
            prefix: {{ $apps.merlin.ui }}
      route:
        - destination:
            host: {{ $apps.merlin.uiServiceName}}
            port:
              number: 8080
    {{- end }}
    {{- end }}
    {{- if .Values.pipeline.enabled}}
    {{- with .Values.pipeline }}
    - name: "pipeline-ui"
      match:
      {{- toYaml .pipelineUI.match | nindent 8 }}
      route:
        {{- toYaml .pipelineUI.route | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.turing.enabled }}
    {{- with .Values.turing }}
    - name: "turing-ui"
      match:
      {{- toYaml .turingUI.match | nindent 8 }}
      route:
        {{- toYaml .turingUI.route | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.xp.enabled }}
    {{- with .Values.xp }}
    - name: "turing-experiments-ui"
      match:
      {{- toYaml .turingXpUI.match | nindent 8 }}
      route:
        {{- toYaml .turingXpUI.route | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.mlp.enabled }}
    {{- with .Values.mlp }}
    - name: "mlp-ui-console"
      route:
        {{- toYaml .mlpUIConsole.route | nindent 8 }}
    {{- end }}
    {{- end }}
