{{- $ingressIP := include "common.istio-lookup" .Values.global }}
{{- if .Values.mlflow.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" (include "caraml-routes.fullname" . ) "mlp-mlflow-vs" }}
  namespace: {{ ternary .Release.Namespace .Values.namespace (ne .Values.namespace "") }}
  labels:
    {{- include "caraml-routes.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.mlflow.vs.hosts }}
    - {{ include "common.localiseDomain" (list . $ingressIP $.Values.global.domain ) }}
    {{- end}}
  gateways:
    - {{ include "caraml-routes.mlp-gateway" . }}
  http:
    - route:
        - destination:
            host: {{ .Values.mlflow.vs.route.destination }}
            port:
              number: {{ .Values.mlflow.vs.route.port }}
{{- end }}
