apiVersion: v1
kind: Service
metadata:
  name: {{ template "feast_ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast_ui.fullname" . }}
    chart: {{ template "feast_ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.feast_ui.labels }}
{{ toYaml .Values.feast_ui.labels | indent 4 -}}
{{- end }}
spec:
  type: {{ .Values.feast_ui.service.type }}
  ports:
    - port: {{ .Values.feast_ui.service.externalPort }}
      targetPort: {{ .Values.feast_ui.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "feast_ui.fullname" . }}
    release: {{ .Release.Name }}