apiVersion: v2
appVersion: 0.8.0
dependencies:
- alias: knativeServingIstio
  condition: knativeServingIstio.enabled
  name: generic-dep-installer
  repository: https://caraml-dev.github.io/helm-charts
  version: 0.2.1
- alias: certManagerBase
  condition: certManagerBase.enabled
  name: cert-manager-base
  repository: https://caraml-dev.github.io/helm-charts
  version: 1.8.1
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.8.2
description: A Helm chart for installing Kserve
maintainers:
- email: caraml-dev@caraml.dev
  name: caraml-dev
name: kserve
type: application
version: 0.8.14
