name: Upgrade helm charts minor versions

on:
  workflow_run:
    workflows: ["Release Charts"]
    types: [completed]

jobs:
  upgrade-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: install pyaml
        run: |
          pip3 install pyaml==21.10.1

      - name: install updateCli
        run: |
          curl -sL -o /tmp/updatecli_amd64.deb https://github.com/updatecli/updatecli/releases/download/v0.36.0/updatecli_amd64.deb
          sudo apt install /tmp/updatecli_amd64.deb

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
        with:
          version: v3.5.1

      - name: Run chart bumper script & update docs
        run: |
          python scripts/chart_bumper.py
          rm -f manifest.yaml
          rm -f manifest_gdi_dependant.yaml
          bash scripts/helm-docs.sh

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/config/ct.yaml | tr '\n' ' ')
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: steps.list-changed.outputs.changed == 'true'
        with:
          commit-message: "feat: upgrade helm charts"
          title: "chore: upgrade helm charts minor versions"
          body: |
            Automatic upgrade of helm chart minor versions using https://github.com/updatecli/updatecli
          branch: upgrade-helm-charts-minors
          base: main
