name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale),
      # yamllint (https://github.com/adrienverge/yamllint) which require Python and
      # generate-creds step below which uses python to parse yaml file.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/config/ct.yaml | tr '\n' ' ')
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=charts_changed::$changed"
          fi

      - name: Add dependency chart repos
        run: |
          helm repo add caraml https://caraml-dev.github.io/helm-charts/
          helm repo add istio https://istio-release.storage.googleapis.com/charts
          helm repo add stable https://charts.helm.sh/stable
          helm repo add cert-manager https://charts.jetstack.io
          helm repo add hashicorp https://helm.releases.hashicorp.com

      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/ct.yaml

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          ./scripts/helm-docs.sh
          if [[ $(git diff --stat **/README.md) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated! ❌\nCheck Contributing Guidelines to know how to update documentation\033[0m'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:v1.22.7

      - name: Install metallb in kind cluster for load balancer services
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ./scripts/install_metallib.sh

      - name: Add cluster credentials as a file if merlin is being installed
        env:
          CHARTS_CHANGED: ${{ steps.list-changed.outputs.charts_changed }}
        run: |
          if [[ $(echo $CHARTS_CHANGED | grep 'charts/\(merlin\|caraml\)') ]]; then
            ./scripts/generate-cluster-creds.sh kind chart-testing
          fi

      - name: Run chart-testing (install)
        run: ct install --config .github/config/ct.yaml --excluded-charts kserve

      - name: Run chart-testing for kserve (install)
        env:
          CHARTS_CHANGED: ${{ steps.list-changed.outputs.charts_changed }}
        run: |
          if [[ $(echo $CHARTS_CHANGED | grep 'charts/kserve') ]]; then
            ct install --charts charts/kserve --namespace kserve --helm-extra-set-args "--create-namespace" --debug
          fi
