apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  labels:
    {{- include "kserve.labels" . | nindent 4 }}
spec:
  commonName: kserve-webhook-server-service.kserve.svc
  dnsNames:
  - kserve-webhook-server-service.kserve.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kserve-webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  labels:
    {{- include "kserve.labels" . | nindent 4 }}
spec:
  selfSigned: {}
