apiVersion: v1
kind: Service
metadata:
  name: kserve-webhook-server-service
  labels:
    {{- include "kserve.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    control-plane: kserve-controller-manager
